# 当前项目唯一运行配置（实际用于测试环境）。
# Web 服务配置参考：https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8001"
  readTimeout: "15s"
  writeTimeout: "30s"
  idleTimeout: "60s"
  maxHeaderBytes: 16384
  clientMaxBodySize: 1048576

# 日志配置参考：https://goframe.org/docs/core/glog-config
logger:
  level : "info"
  stdout: true

# 数据库配置参考：https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/security_permission?loc=Local&parseTime=true&charset=utf8mb4"
    maxIdle: 10
    maxOpen: 30
    maxLifeTime: "30m"
    maxIdleTime: "10m"
    queryTimeout: "5s"
    execTimeout: "10s"
    tranTimeout: "15s"
