-- =============================================================================
-- 当前内置菜单/功能权限点。数据库由 dbinit 全量重建,这里直接插入基线数据。
-- =============================================================================
USE `security_permission`;
SET NAMES utf8mb4;

INSERT INTO `menu` (`code`,`parent_code`,`name`,`domain`) VALUES
 ('sys.person','','人员管理','SYS'),
 ('sys.person.info','sys.person','人员信息','SYS'),
 ('sys.person.role','sys.person','角色管理','SYS'),
 ('sys.person.account','sys.person','账号管理','SYS'),
 ('sys.person.face','sys.person','人脸管理','SYS'),
 ('sys.business','','业务数据管理','SYS'),
 ('sys.business.passenger','sys.business','客流统计','SYS'),
 ('sys.vehicle','','车辆信息管理','SYS'),
 ('sys.area','','安保区域管理','SYS'),
 ('sys.device','','设备管理','SYS'),
 ('sys.device.encode','sys.device','编码设备','SYS'),
 ('sys.device.broadcast','sys.device','广播设备','SYS'),
 ('sys.device.alarm','sys.device','报警设备','SYS'),
 ('sys.resource','','资源管理','SYS'),
 ('sys.resource.point','sys.resource','监控点','SYS'),
 ('sys.resource.terminal','sys.resource','终端','SYS'),
 ('sys.resource.io','sys.resource','报警输入输出','SYS'),
 ('sys.resource.zone','sys.resource','防区','SYS'),
 ('sys.videocfg','','视频监控配置','SYS'),
 ('sys.videocfg.record','sys.videocfg','录像计划','SYS'),
 ('sys.videocfg.capture','sys.videocfg','抓图计划','SYS'),
 ('sys.videocfg.defense','sys.videocfg','事件布撤防','SYS'),
 ('sys.videocfg.param','sys.videocfg','参数配置','SYS'),
 ('sys.servicecfg','','综合服务配置','SYS'),
 ('sys.servicecfg.event','sys.servicecfg','事件联动','SYS'),
 ('sys.servicecfg.map','sys.servicecfg','地图配置','SYS'),
 ('sys.servicecfg.recognition','sys.servicecfg','识别计划配置','SYS'),
 ('sys.network','','网络配置管理','SYS'),
 ('sys.network.patrol','sys.network','巡检计划配置','SYS'),
 ('sys.advanced','','高级系统管理','SYS'),
 ('sys.advanced.param','sys.advanced','高级参数配置','SYS'),
 ('sys.advanced.platform-upgrade','sys.advanced','平台升级管理','SYS'),
 ('sys.advanced.app-upgrade','sys.advanced','APP升级管理','SYS'),
 ('sys.advanced.stream-upgrade','sys.advanced','流媒体升级管理','SYS'),
 ('sys.advanced.sms','sys.advanced','短信管理','SYS'),
 ('sys.advanced.email','sys.advanced','邮箱管理','SYS'),
 ('app.integrated','','综合管控','APP'),
 ('app.integrated.eventsearch','app.integrated','事件检索','APP'),
 ('app.integrated.mapmonitor','app.integrated','图上监控','APP'),
 ('app.integrated.smartsearch','app.integrated','智能检索','APP'),
 ('app.integrated.broadcast','app.integrated','广播','APP'),
 ('app.video','','视频监控','APP'),
 ('app.video.live','app.video','实时预览','APP'),
 ('app.video.playback','app.video','远程回放','APP'),
 ('app.video.picture','app.video','图片查询','APP'),
 ('app.network','','网络管控','APP'),
 ('app.network.monitor','app.network','视频网管监控','APP');
