package consts

// 系统管理端菜单与功能权限码。
const (
	MenuCodeSysPerson                   = "sys.person"
	MenuCodeSysPersonInfo               = "sys.person.info"
	MenuCodeSysPersonRole               = "sys.person.role"
	MenuCodeSysPersonAccount            = "sys.person.account"
	MenuCodeSysPersonFace               = "sys.person.face"
	MenuCodeSysBusiness                 = "sys.business"
	MenuCodeSysBusinessPassenger        = "sys.business.passenger"
	MenuCodeSysVehicle                  = "sys.vehicle"
	MenuCodeSysArea                     = "sys.area"
	MenuCodeSysDevice                   = "sys.device"
	MenuCodeSysDeviceEncode             = "sys.device.encode"
	MenuCodeSysDeviceBroadcast          = "sys.device.broadcast"
	MenuCodeSysDeviceAlarm              = "sys.device.alarm"
	MenuCodeSysResource                 = "sys.resource"
	MenuCodeSysResourcePoint            = "sys.resource.point"
	MenuCodeSysResourceTerminal         = "sys.resource.terminal"
	MenuCodeSysResourceIO               = "sys.resource.io"
	MenuCodeSysResourceZone             = "sys.resource.zone"
	MenuCodeSysVideoConfig              = "sys.videocfg"
	MenuCodeSysVideoConfigRecord        = "sys.videocfg.record"
	MenuCodeSysVideoConfigCapture       = "sys.videocfg.capture"
	MenuCodeSysVideoConfigDefense       = "sys.videocfg.defense"
	MenuCodeSysVideoConfigParam         = "sys.videocfg.param"
	MenuCodeSysServiceConfig            = "sys.servicecfg"
	MenuCodeSysServiceConfigEvent       = "sys.servicecfg.event"
	MenuCodeSysServiceConfigMap         = "sys.servicecfg.map"
	MenuCodeSysServiceConfigRecognition = "sys.servicecfg.recognition"
	MenuCodeSysNetwork                  = "sys.network"
	MenuCodeSysNetworkPatrol            = "sys.network.patrol"
	MenuCodeSysAdvanced                 = "sys.advanced"
	MenuCodeSysAdvancedParam            = "sys.advanced.param"
	MenuCodeSysAdvancedPlatformUpgrade  = "sys.advanced.platform-upgrade"
	MenuCodeSysAdvancedAppUpgrade       = "sys.advanced.app-upgrade"
	MenuCodeSysAdvancedStreamUpgrade    = "sys.advanced.stream-upgrade"
	MenuCodeSysAdvancedSMS              = "sys.advanced.sms"
	MenuCodeSysAdvancedEmail            = "sys.advanced.email"
)

// 应用端菜单与功能权限码。
const (
	MenuCodeAppIntegrated            = "app.integrated"
	MenuCodeAppIntegratedEventSearch = "app.integrated.eventsearch"
	MenuCodeAppIntegratedMapMonitor  = "app.integrated.mapmonitor"
	MenuCodeAppIntegratedSmartSearch = "app.integrated.smartsearch"
	MenuCodeAppIntegratedBroadcast   = "app.integrated.broadcast"
	MenuCodeAppVideo                 = "app.video"
	MenuCodeAppVideoLive             = "app.video.live"
	MenuCodeAppVideoPlayback         = "app.video.playback"
	MenuCodeAppVideoPicture          = "app.video.picture"
	MenuCodeAppNetwork               = "app.network"
	MenuCodeAppNetworkMonitor        = "app.network.monitor"
)
