// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"security-permission/internal/dao/internal"
)

// actionDao is the data access object for the table action.
// You can define custom methods on it to extend its functionality as needed.
type actionDao struct {
	*internal.ActionDao
}

var (
	// Action is a globally accessible object for table action operations.
	Action = actionDao{internal.NewActionDao()}
)

// Add your custom methods and functionality below.
