// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"security-permission/internal/dao/internal"
)

// areaDao is the data access object for the table area.
// You can define custom methods on it to extend its functionality as needed.
type areaDao struct {
	*internal.AreaDao
}

var (
	// Area is a globally accessible object for table area operations.
	Area = areaDao{internal.NewAreaDao()}
)

// Add your custom methods and functionality below.
