// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"security-permission/internal/dao/internal"
)

// orgDao is the data access object for the table org.
// You can define custom methods on it to extend its functionality as needed.
type orgDao struct {
	*internal.OrgDao
}

var (
	// Org is a globally accessible object for table org operations.
	Org = orgDao{internal.NewOrgDao()}
)

// Add your custom methods and functionality below.
