// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"security-permission/internal/dao/internal"
)

// resourceDao is the data access object for the table resource.
// You can define custom methods on it to extend its functionality as needed.
type resourceDao struct {
	*internal.ResourceDao
}

var (
	// Resource is a globally accessible object for table resource operations.
	Resource = resourceDao{internal.NewResourceDao()}
)

// Add your custom methods and functionality below.
