// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"security-permission/internal/dao/internal"
)

// roleResourceActionDao is the data access object for the table role_resource_action.
// You can define custom methods on it to extend its functionality as needed.
type roleResourceActionDao struct {
	*internal.RoleResourceActionDao
}

var (
	// RoleResourceAction is a globally accessible object for table role_resource_action operations.
	RoleResourceAction = roleResourceActionDao{internal.NewRoleResourceActionDao()}
)

// Add your custom methods and functionality below.
