// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"security-permission/internal/dao/internal"
)

// roleDataScopeDao is the data access object for the table role_data_scope.
// You can define custom methods on it to extend its functionality as needed.
type roleDataScopeDao struct {
	*internal.RoleDataScopeDao
}

var (
	// RoleDataScope is a globally accessible object for table role_data_scope operations.
	RoleDataScope = roleDataScopeDao{internal.NewRoleDataScopeDao()}
)

// Add your custom methods and functionality below.
